### ISSUE TITLE
exportxml: export to dot fails b/c of unicode issues

### ISSUE THREAD

**Issue by arne-cl** [arne-cl/discoursegraphs#116]
content of exportxml_test.py:

```python
import os
import discoursegraphs as dg
import igraph

TUEBADZ_FILE = os.path.expanduser(
    '~/corpora/tueba/tuebadz-5.0/data/XML/tuebadz-5.0.anaphora.export.xml')

edg = dg.read_exportxml(TUEBADZ_FILE, limit=2)
igraph.write(edg, '/tmp/igraph.dot')
```

result:

```
/usr/local/lib/python2.7/dist-packages/igraph/__init__.py:2280: RuntimeWarning: A non-numeric, non-string, non-boolean vertex attribute was ignored at foreign.c:2892
  return writer(f, *args, **kwds)
Traceback (most recent call last):
  File "logtest.py", line 9, in <module>
    igraph.write(edg, '/tmp/igraph.dot')
  File "/usr/local/lib/python2.7/dist-packages/igraph/__init__.py", line 4075, in write
    return graph.write(filename, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/igraph/__init__.py", line 2280, in write
    return writer(f, *args, **kwds)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 2: ordinal not in range(128)
```

**Comment by arne-cl** [comment]
This doesn't apply any more, as the exporter has been completely rewritten.
