### ISSUE TITLE
neonx: unrecognized keyword `edge_rel_attrib`

### ISSUE THREAD

**Issue by WladimirSidorenko** [arne-cl/discoursegraphs#132]
1. Environment:
```
pip show discoursegraphs
---
Metadata-Version: 1.0
Name: discoursegraphs
Version: 0.1.2
Summary: graph-based processing of multi-level annotated corpora
Home-page: https://github.com/arne-cl/discoursegraphs
Author: Arne Neumann
Author-email: discoursegraphs.programming@arne.cl
License: 3-Clause BSD License
Location: /usr/local/lib/python2.7/site-packages
Requires: nltk, enum, lxml, networkx, pygraphviz, brewer2mpl, unidecode, neonx, pydot2
Entry-points:
  [console_scripts]
  discoursegraphs = discoursegraphs.merging:merging_cli

pip show neonx
---
Metadata-Version: 2.0
Name: neonx
Version: 0.1.1
Summary: Handles conversion of date from NetworkX graph to Neo4j
Home-page: https://github.com/ducky427/neonx
Author: Rohit Aggarwal
Author-email: rohit.neonx@mailnull.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: networkx, requests

python --version
Python 2.7.3

name -srm
Linux 3.4.63-2.44-desktop x86_64
```

2. Steps to reproduce (with pcc-2.0):
```
discoursegraphs -t potsdam-commentary-corpus-2.0.0/syntax/maz-13153.xml -r potsdam-commentary-corpus-2.0.0/rst/maz-13153.rs3 -c potsdam-commentary-corpus-2.0.0/connectors/maz-13153.xml -m potsdam-commentary-corpus-2.0.0/coreference/maz-13153.mmax -o neo4j
Traceback (most recent call last):
  File "/usr/local/bin/discoursegraphs", line 9, in <module>
    load_entry_point('discoursegraphs==0.1.2', 'console_scripts', 'discoursegraphs')()
  File "/usr/local/lib/python2.7/site-packages/discoursegraphs/merging.py", line 118, in merging_cli
    upload_to_neo4j(discourse_docgraph)
  File "/usr/local/lib/python2.7/site-packages/discoursegraphs/readwrite/neo4j.py", line 85, in upload_to_neo4j
    label_name='discoursegraph:fallback_label')
TypeError: write_to_neo() got an unexpected keyword argument 'edge_rel_attrib'
```

**Comment by arne-cl** [comment]
I don't have `neo4j` installed on my machine right now. Do you get the same error if you use the `-o geoff` output option? (This one works on my machine.)

**Comment by WladimirSidorenko** [comment]
with `geoff` everything works fine, but do you need `neo4j` for testing `neonx` library?

**Comment by arne-cl** [comment]
Yes, you'll need a running instance of neo4j on your local machine to use the `-o neo4j` option. This will export the data and directly push it to your server. If you just need neo4j-compatible data, `-o geoff` is the
right option.

When I use the `neo4j` output option, I get a different error than you.

```python
arne@tinybrick ~/corpora $ discoursegraphs -t potsdam-commentary-corpus-2.0.0/syntax/maz-13153.xml -r potsdam-commentary-corpus-2.0.0/rst/maz-13153.rs3 -c potsdam-commentary-corpus-2.0.0/connectors/maz-13153.xml -m potsdam-commentary-corpus-2.0.0/coreference/maz-13153.mmax -o neo4j
Traceback (most recent call last):
  File "/usr/local/bin/discoursegraphs", line 9, in <module>
    load_entry_point('discoursegraphs==0.1.2', 'console_scripts', 'discoursegraphs')()
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs-0.1.2-py2.7.egg/discoursegraphs/merging.py", line 118, in merging_cli
    upload_to_neo4j(discourse_docgraph)
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs-0.1.2-py2.7.egg/discoursegraphs/readwrite/neo4j.py", line 85, in upload_to_neo4j
    label_name='discoursegraph:fallback_label')
  File "/usr/local/lib/python2.7/dist-packages/neonx-0.1.1-py2.7.egg/neonx/neo.py", line 227, in write_to_neo
    all_server_urls = get_server_urls(server_url)
  File "/usr/local/lib/python2.7/dist-packages/neonx-0.1.1-py2.7.egg/neonx/neo.py", line 156, in get_server_urls
    check_exception(result)
  File "/usr/local/lib/python2.7/dist-packages/neonx-0.1.1-py2.7.egg/neonx/neo.py", line 139, in check_exception
    e = Exception(result_json['exception'])
KeyError: 'exception'
```

After installing neo4j 2.3 and debugging this call with `pudb`, I found that the error occurs with
new(er) versions of neo4j, which require authorization:

```python
>>> result.content
'{\n  "errors" : [ {\n    "message" : "No authorization header supplied.",\n    "code" : "Neo.ClientError.Security.AuthorizationFailed"\n  } ]\n}'
```

BTW, please don't install the `discoursegraphs` and `neonx` via pip, but directly from my github repos. `discoursegraphs` on pip is outdated, while `neonx` is the original, but I need my own fork to run correctly.

**Comment by arne-cl** [comment]
There's also a docker file that will allow you to install the whole thing in one step: 
https://github.com/nlpdocker/discoursegraphs-docker

**Comment by WladimirSidorenko** [comment]
The problem still repeats with a running no4j instance. I think the reason is that the [newest version](https://neonx.readthedocs.org/en/latest/neonx.html) of  `neonx`  does not support the `edge_rel_attrib'` attribute for the `write_to_neo` method any longer.

**Comment by arne-cl** [comment]
The official "newest" version does not have this feature. It is only present in my (and @erickpeirson's) fork. I will now add the authentification part, which became mandatory with recent versions of Neo4j.

http://stackoverflow.com/questions/29828635/neo4j-simple-authentication
