### ISSUE TITLE
'MMAXDocumentGraph' object has no attribute 'renamed_nodes'

### ISSUE THREAD

**Issue by WladimirSidorenko** [arne-cl/discoursegraphs#134]
Description:
----------------
Two files of `PCC 2.0` (`maz-00001` and `maz-17953`) cause the following errors while converting to `geoff`:
```
>discoursegraphs -t pcc/potsdam-commentary-corpus-2.0.0/syntax/maz-17953.xml -r pcc/potsdam-commentary-corpus-2.0.0/rst/maz-17953.rs3 -c pcc/potsdam-commentary-corpus-2.0.0/connectors/maz-17953.xml -m pcc/potsdam-commentary-corpus-2.0.0/coreference/maz-17953.mmax -o geoff
Traceback (most recent call last):
  File "/usr/local/bin/discoursegraphs", line 9, in <module>
    load_entry_point('discoursegraphs==0.1.2', 'console_scripts', 'discoursegraphs')()
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs/merging.py", line 84, in merging_cli
    mmax_graph = MMAXDocumentGraph(args.mmax_file)
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs/readwrite/mmax2.py", line 157, in __init__
    self.add_annotation_layer(annotation_file, layer_name)
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs/readwrite/mmax2.py", line 288, in add_annotation_layer
    for target_node_id in spanstring2tokens(self, markable.attrib['span']):
  File "/usr/local/lib/python2.7/dist-packages/discoursegraphs/readwrite/mmax2.py", line 430, in spanstring2tokens
    renamed_token_id = docgraph.renamed_nodes.get(tok)
AttributeError: 'MMAXDocumentGraph' object has no attribute 'renamed_nodes'

```

**Comment by arne-cl** [comment]
This is the second bug I "rediscovered" this weekend. \*sigh\*

**Comment by arne-cl** [comment]
``data/potsdam-commentary-corpus-2.0.0/coreference/basedata/maz-00001_words.xml``
contains this gem:

```
<word id="word_81">soll</word>
<!-- <word id="word_82"> </word> removed empty soft-hyphen word //AN 20131101 -->
<word id="word_83">auf</word>
```

while ``data/potsdam-commentary-corpus-2.0.0/coreference/basedata/maz-17953_words.xml``
has this:

```
<word id="word_192">Probleme</word>
<!--not part of original data <word id="word_193">der</word> // AN, 2014-06-05 -->
<word id="word_194">Gesellschaft</word>
```

The function ``spanstring2tokens`` trips over those non-existing <word> elements
and assumes that this was caused by some graph merge operation.

```python
    existing_nodes = set(docgraph.nodes())

    existing_tokens = []
    for tok in tokens:
        if tok in existing_nodes:
            existing_tokens.append(tok)
        else: # we're trying to catch all token IDs that have been
              # renamed during merging of document graphs / annotation layers
            renamed_token_id = docgraph.renamed_nodes.get(tok)
            if renamed_token_id in existing_nodes:
                existing_tokens.append(renamed_token_id)
```

Since there was no merging going on, ``docgraph`` has no attribute ``renamed_nodes``.
